if three_shot == false
{
	buffer_seek(con_client.client_buffer,buffer_seek_start,0);
	buffer_write(con_client.client_buffer,buffer_u8,NETWORK_CLIENT.SHOOT);
	buffer_write(con_client.client_buffer,buffer_bool,true);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.image_angle);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.x);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.y);
	network_send_packet(con_client.client,con_client.client_buffer,buffer_tell(con_client.client_buffer))
}
else
{
	buffer_seek(con_client.client_buffer,buffer_seek_start,0);
	buffer_write(con_client.client_buffer,buffer_u8,NETWORK_CLIENT.POWER_SHOOT);
	buffer_write(con_client.client_buffer,buffer_bool,true);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.image_angle);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.x);
	buffer_write(con_client.client_buffer,buffer_u16,obj_player_client.y);
	network_send_packet(con_client.client,con_client.client_buffer,buffer_tell(con_client.client_buffer))
}